export interface ICoin { 
    blockchain?: string,
    deposit?: number,
    fee_widthdraw?: number,
    id?: number,
    image?: string,
    lendding?: number,
    minimum_widthdraw?: number,
    name?: string,
    p2p?: number,
    percent: number,
    price?: number | any,
    staking?: number,
    swap?: number,
    symbolWallet?: string,
    token_key?: string,
    type?: string,
    volume?: number,
}
