export const screens = {
    AD: 'AD',
    MAIN: 'Main',
    SWAP: 'Swap',
    HELLO: 'Hello',
    LOGIN: 'Login',
    WALLET: 'Wallet',
    SETTING: 'Setting',
    AD_STACK: 'ADStack',
    LANGUAGE: 'Language',
    REGISTER: 'Register',
    SWAP_STACK: 'SwapStack',
    WALLET_STACK: 'WalletStack',
    SETTING_STACK: 'SettingStack',
    TOP_TAB_WALLET: 'TopTabWallet',
    TURN_ON_2FA: 'TurnOn2FA',
    TWO_FACTOR_AUTHENTICATION: 'TwoFactorAuthentication',
    KYC: 'KYC',
    VERIFY2FA: 'Verify2FA',
    ECOSYSTEM: 'Ecosystem',
    TRANSACTION: 'Transaction',
    CONFIRM_TRANSACTION: 'ConfirmTransaction',
    HISTORY_TRANSACTION: 'HistoryTransaction',
}